apiVersion: "2.0"
kind: "ServiceConfig"
metadata:
  serviceConfigVersion: 1.0
  serviceId: AEX_SIZE_AND_PACK
  authzPolicies:
    adminUI:
      adminGroups:
        - "apparel-precision-kitt"
    git:
      org: "ApparelPrecision"
      repo: "aex-size-and-pack"
      branch: "main"
  notifications:
    slack:
      channel: apparel-precision-ops
configDefinitions:
  databaseConfig:
    description: ""
    resolutionPaths:
      - default: "/envProfile/envName"
    properties:
      "sqlServer.url":
        description: "SP SQL Server DB URL"
        type: "STRING"
        kind: "SINGLE"
        defaultValue: "jdbc:sqlserver://us-wm-aex-dev-spo-nonprod-625febf5.database.windows.net:1433;database=us_wm_aex_spo;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;authentication=ActiveDirectoryPassword"
      "sqlServer.driverClassName":
        description: "SQL Server Driver Class Name"
        type: "STRING"
        kind: "SINGLE"
        defaultValue: "com.microsoft.sqlserver.jdbc.SQLServerDriver"
      "sqlServer.connection.pool.initial.size":
        description: "Connection Pool Initial Size"
        type: "INTEGER"
        kind: "SINGLE"
        defaultValue: 3
      "sqlServer.connection.max.active":
        description: "Max Active Connections"
        type: "INTEGER"
        kind: "SINGLE"
        defaultValue: 5
      "sqlServer.connection.timeout.ms":
        description: "Connection Timeout in milliseconds"
        type: "INTEGER"
        kind: "SINGLE"
        defaultValue: 30000
      "sqlServer.connection.max.life.time.ms":
        description: "Max connection lifetime in milliseconds"
        type: "INTEGER"
        kind: "SINGLE"
        defaultValue: 180000
      "sqlServer.connection.idle.timeout.ms":
        description: "Idle connection timeout in milliseconds"
        type: "INTEGER"
        kind: "SINGLE"
        defaultValue: 30000