apiVersion: "2.0"
kind: "ServiceConfig"
metadata:
  serviceConfigVersion: 1.0
  serviceId: AEX_SIZE_AND_PACK
  authzPolicies:
    adminUI:
      adminGroups:
        - "apparel-precision-kitt"
    git:
      org: "ApparelPrecision"
      repo: "aex-size-and-pack"
      branch: "main"
  notifications:
    slack:
      channel: apparel-precision-ops
configDefinitions:
  databaseConfig:
    description: ""
    resolutionPaths:
      - default: "/envProfile/envName"
    properties:
      "sqlServer.url":
        description: "SP SQL Server DB URL"
        type: "STRING"
        kind: "SINGLE"
        defaultValue: "jdbc:sqlserver://us-wm-aex-dev-spo-nonprod-625febf5.database.windows.net:1433;database=us_wm_aex_spo;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;authentication=ActiveDirectoryPassword"
      "sqlServer.driverClassName":
        description: "SQL Server Driver Class Name"
        type: "STRING"
        kind: "SINGLE"
        defaultValue: "com.microsoft.sqlserver.jdbc.SQLServerDriver"
      "sqlServer.connection.pool.initial.size":
        description: "Connection Pool Initial Size"
        type: "INTEGER"
        kind: "SINGLE"
        defaultValue: 3
      "sqlServer.connection.max.active":
        description: "Max Active Connections"
        type: "INTEGER"
        kind: "SINGLE"
        defaultValue: 5
      "sqlServer.connection.timeout.ms":
        description: "Connection Timeout in milliseconds"
        type: "INTEGER"
        kind: "SINGLE"
        defaultValue: 30000
      "sqlServer.connection.max.life.time.ms":
        description: "Max connection lifetime in milliseconds"
        type: "INTEGER"
        kind: "SINGLE"
        defaultValue: 180000
      "sqlServer.connection.idle.timeout.ms":
        description: "Idle connection timeout in milliseconds"
        type: "INTEGER"
        kind: "SINGLE"
        defaultValue: 30000
  bqfpServiceConfig:
    description: ""
    resolutionPaths:
      - default: "/envProfile/envName"
    properties:
      "bqfp.url":
        description: "BQFP Service URL"
        type: "STRING"
        kind: "SINGLE"
        defaultValue: "https://flow-plan.aex.dev.walmart.net/flow-plan/v1/getBuyQtyFromFlowPlan"
      "bqfp.consumerId":
        description: "BQFP SR Consumer ID"
        type: "STRING"
        kind: "SINGLE"
        defaultValue: "34f7ca77-3dfc-46df-a86b-1ba6e4908d0e"
      "bqfp.env":
        description: "BQFP SR Env"
        type: "STRING"
        kind: "SINGLE"
        defaultValue: "dev"
      "bqfp.svcName":
        description: "BQFP SR Service Name"
        type: "STRING"
        kind: "SINGLE"
        defaultValue: "AEX_FLOW_PLAN"
  httpConfig:
    description: "HTTP Configurations"
    resolutionPaths:
      - default: "/envProfile/envName"
    properties:
      "http.connectTimeout":
        description: "Connection Timeout for HTTP Calls"
        type: "INTEGER"
        kind: "SINGLE"
        defaultValue: 18000
      "http.connectionRequestTimeout":
        description: "Connection Request Timeout for HTTP Calls"
        type: "INTEGER"
        kind: "SINGLE"
        defaultValue: 18000
      "http.readTimeout":
        description: "Read Timeout for HTTP calls"
        type: "INTEGER"
        kind: "SINGLE"
        defaultValue: 18000
  graphQlConfig:
    description: "GraphQL Config"
    resolutionPaths:
      - default: "/envProfile/envName"
    properties:
      "size.profile.url":
        description: "Get Size Profile URL from strategy Service"
        type: "STRING"
        kind: "SINGLE"
        defaultValue: "https://strategy.aex.dev.walmart.net/graphql"
      "size.profile.query":
        description: "Size Profile Query for GraphQL Call"
        type: "STRING"
        kind: "SINGLE"
        defaultValue: "query ($sizeProfileRequest:SizeProfileRequest!)\n {\n getCcSizeClus(sizeProfileRequest:  $sizeProfileRequest)\n {\n planId\n lvl0Nbr\n lvl1Nbr\n lvl2Nbr\n lvl3List{\n lvl3Nbr\n lvl4List{\n lvl4Nbr\n finelines{\n finelineNbr\n styles{\n styleNbr\n customerChoices{\n ccId\n clusters{\n clusterID\n sizes{\n ahsSizeId\n sizeDesc\n metrics{\n sizeProfilePct\n adjSizeProfilePct\n avgSizeProfilePct\n adjAvgSizeProfilePct\n }}}}}}}}}}"
      "size.profile.all.cc.query":
        description: "Get All CC's Size Profile Query for GraphQL Call"
        type: "STRING"
        kind: "SINGLE"
        defaultValue: "query ($sizeProfileRequest:SizeProfileRequest!)\n {\n getAllCcSizeClus(sizeProfileRequest:  $sizeProfileRequest)\n {\n planId\n lvl0Nbr\n lvl1Nbr\n lvl2Nbr\n lvl3List{\n lvl3Nbr\n lvl4List{\n lvl4Nbr\n finelines{\n finelineNbr\n merchMethods{\n fixtureTypeRollupId\n merchMethod\n }\n metrics{\n sizeProfilePct\n adjSizeProfilePct\n avgSizeProfilePct\n adjAvgSizeProfilePct\n }\n clusters{\n clusterID\n sizes{\n ahsSizeId\n sizeDesc\n metrics{\n sizeProfilePct\n adjSizeProfilePct\n avgSizeProfilePct\n adjAvgSizeProfilePct\n }\n }\n }\n styles{\n styleNbr\n metrics{\n sizeProfilePct\n adjSizeProfilePct\n avgSizeProfilePct\n adjAvgSizeProfilePct\n }\n clusters{\n clusterID\n sizes{\n ahsSizeId\n sizeDesc\n metrics{\n sizeProfilePct\n adjSizeProfilePct\n avgSizeProfilePct\n adjAvgSizeProfilePct\n }\n }\n }\n customerChoices{\n ccId\n metrics{\n sizeProfilePct\n adjSizeProfilePct\n avgSizeProfilePct\n adjAvgSizeProfilePct\n }\n clusters{\n clusterID\n sizes{\n ahsSizeId\n sizeDesc\n metrics{\n sizeProfilePct\n adjSizeProfilePct\n avgSizeProfilePct\n adjAvgSizeProfilePct\n }}}}}}}}}}"
      "size.profile.consumer.id":
        description: "Consumer ID to call Strategy Service"
        type: "STRING"
        kind: "SINGLE"
        defaultValue: "19ce2bf5-4c24-4bbf-bee9-84496dd07e3c"
      "size.profile.consumer.name":
        description: "Consumer service name"
        type: "STRING"
        kind: "SINGLE"
        defaultValue: "AEX_STRATEGY_SERVICE"
      "size.profile.consumer.env":
        description: "Consumer Environment"
        type: "STRING"
        kind: "SINGLE"
        defaultValue: "dev"
      "size.profile.assortproduct.url":
        description: "Get RFA output from Assort Product Service"
        type: "STRING"
        kind: "SINGLE"
        defaultValue: "https://assortproduct.aex.dev.walmart.net/graphql"
      "size.profile.assortproduct.query":
        description: "Query to retrieve RFA output"
        type: "STRING"
        kind: "SINGLE"
        defaultValue: "query($request:RFASizePackRequest!){getRFADataFromSizePack(rfaSizePackRequest:$request){rfaSizePackData{rpt_lvl_0_nbr rpt_lvl_1_nbr rpt_lvl_2_nbr rpt_lvl_3_nbr rpt_lvl_4_nbr fineline_nbr style_nbr customer_choice fixture_type fixture_group color_family size_cluster_id volume_group_cluster_id store_list store_cnt plan_id_partition}}}"
      "size.profile.assortproduct.consumer.id":
        description: "Consumer ID to call Assort Product"
        type: "STRING"
        kind: "SINGLE"
        defaultValue: "19ce2bf5-4c24-4bbf-bee9-84496dd07e3c"
      "size.profile.assortproduct.consumer.name":
        description: "Consumer service name"
        type: "STRING"
        kind: "SINGLE"
        defaultValue: "AEX_ASSORTPRODUCT_SERVICE"
      "size.profile.assortproduct.consumer.env":
        description: "Consumer Environment"
        type: "STRING"
        kind: "SINGLE"
        defaultValue: "dev"

  integrationHubServiceConfig:
    description: "IntegrationHub Config"
    resolutionPaths:
      - default: "/envProfile/envName"
    properties:
      "integrationhub.url":
        description: "IntegrationHub Service URL"
        type: "STRING"
        kind: "SINGLE"
        defaultValue: "http://analytics-api.stg.us-central1.walmart.net/api/packopt?scenario=pack_optimization_dataproc"
      "integrationhub.sizeAndPackBaseUrl":
        description: "SizeAndPack Base URL"
        type: "STRING"
        kind: "SINGLE"
        defaultValue: "http://aex-size-and-pack.aex.dev.walmart.net"

  buyQtyConfig:
    description: "Buy Quantity Constants Config"
    resolutionPaths:
      - default: "/envProfile/envName"
    properties:
      "initialSet.constraint":
        description: "Initial set threshold"
        type: "INTEGER"
        kind: "SINGLE"
        defaultValue: 2
      "replenishment.constraint":
        description: "Replenishment threshold"
        type: "INTEGER"
        kind: "SINGLE"
        defaultValue: 500

  midasConfig:
    description: "Midas Data API Service to Service Authentication"
    resolutionPaths:
      - default: "/envProfile/envName"
    properties:
      "midas.baseURL":
        description: "Midas api base url"
        type: "STRING"
        kind: "SINGLE"
        defaultValue: "http://midas-data-api.stg.midas-api.catdev.prod.us.walmart.net/api/workflow/v1/execute"
      "midas.clickhouse.table":
        description: "midas clickhouse table"
        type: "STRING"
        kind: "SINGLE"
        defaultValue: "omni_item_channel_sales_wkly_v4_dist"
      "midas.header.contentType":
        description: "Midas api header content type"
        type: "STRING"
        kind: "SINGLE"
        defaultValue: "application/json"
      "midas.header.consumer":
        description: "Midas api header consumer Id"
        type: "STRING"
        kind: "SINGLE"
        defaultValue: "13705f9d-3eb8-46b5-b2c1-63a1b569af4c"
      "midas.header.signatureKeyVersion":
        description: "Midas api header signature Key Version"
        type: "STRING"
        kind: "SINGLE"
        defaultValue: "1"
      "midas.header.signatureAuthFlag":
        description: "Midas api header signature Auth Flag"
        type: "STRING"
        kind: "SINGLE"
        defaultValue: "true"
      "midas.header.signatureTS":
        description: "Midas api header signature TS"
        type: "STRING"
        kind: "SINGLE"
        defaultValue: "1639068838648"
      "midas.header.tenant":
        description: "Midas api header tenant"
        type: "STRING"
        kind: "SINGLE"
        defaultValue: "aex"
      "midas.historicalSizeMetricsQuery":
        description: "JSON query for historical size metrics"
        type: "STRING"
        kind: "SINGLE"
        defaultValue: "{"query":{"select":[{"field":"*"}],"from":"get_historical_size_metrics_fineline_cc","params":{"finelineNbr":%d,"lyCompWeekStart":%d,"lyCompWeekEnd":%d,"lvl0Nbr":%d,"lvl1Nbr":%d,"lvl2Nbr":%d,"lvl3Nbr":%d,"lvl4Nbr":%d,"channel":"%s"}}}"

configOverrides:
  graphQlConfig:
    - name: "stage"
      description: "GraphQL override for STAGE profile"
      pathElements:
        envName: "stage"
        envProfile: "stage"
      value:
        properties:
          "size.profile.url": "https://strategy.aex.stg.walmart.net/graphql"
          "size.profile.assortproduct.url": "https://assortproduct.aex.stg.walmart.net/graphql"
          "size.profile.consumer.id": "93c617a1-31ec-4333-a819-683ef7514cc0"
          "size.profile.consumer.env": "stg"
          "size.profile.assortproduct.consumer.id": "93c617a1-31ec-4333-a819-683ef7514cc0"
          "size.profile.assortproduct.consumer.env": "stg"
  bqfpServiceConfig:
    - name: "stage"
      description: "Flow Plan override for STAGE profile"
      pathElements:
        envName: "stage"
        envProfile: "stage"
      value:
        properties:
          "bqfp.url": "https://flow-plan.aex.stg.walmart.net/flow-plan/v1/getBuyQtyFromFlowPlan"
  databaseConfig:
    - name: "stage"
      description: "DB for STAGE profile"
      pathElements:
        envName: "stage"
        envProfile: "stage"
      value:
        properties:
          "sqlServer.url": "jdbc:sqlserver://us-wm-aex-stg-spo-nonprod-62cd5875.database.windows.net:1433;database=us_wm_aex_spo;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;authentication=ActiveDirectoryPassword"