package com.walmart.aex.sp.repository;

import com.walmart.aex.sp.entity.CcPackOptimization;
import com.walmart.aex.sp.entity.CcPackOptimizationID;
import org.springframework.data.jpa.repository.JpaRepository;

public interface CcPackOptimizationRepository extends JpaRepository<CcPackOptimization, CcPackOptimizationID> {
    void deleteCcPackOptimizationByCcPackOptimizationId_StylePackOptimizationID_finelinePackOptimizationID_SubCatgPackOptimizationID_MerchantPackOptimizationID_planIdAndCcPackOptimizationId_StylePackOptimizationID_finelinePackOptimizationID_SubCatgPackOptimizationID_MerchantPackOptimizationID_repTLvl3AndCcPackOptimizationId_StylePackOptimizationID_finelinePackOptimizationID_SubCatgPackOptimizationID_repTLvl4AndCcPackOptimizationId_StylePackOptimizationID_finelinePackOptimizationID_finelineNbrAndCcPackOptimizationId_StylePackOptimizationID_styleNbrAndCcPackOptimizationId_customerChoice(
            Long planId, Integer repTLvl3, Integer repTLvl4, Integer finelineNbr,String styleNbr, String customerChoice);
}
