package com.walmart.aex.sp.repository;


import com.walmart.aex.sp.entity.StylePackOptimization;
import com.walmart.aex.sp.entity.StylePackOptimizationID;
import org.springframework.data.jpa.repository.JpaRepository;

public interface StylePackOptimizationRepository extends JpaRepository<StylePackOptimization, StylePackOptimizationID> {
    void deleteByStylePackoptimizationId_FinelinePackOptimizationID_SubCatgPackOptimizationID_MerchantPackOptimizationID_planIdAndStylePackoptimizationId_FinelinePackOptimizationID_SubCatgPackOptimizationID_MerchantPackOptimizationID_repTLvl3AndStylePackoptimizationId_FinelinePackOptimizationID_SubCatgPackOptimizationID_repTLvl4AndStylePackoptimizationId_FinelinePackOptimizationID_finelineNbrAndStylePackoptimizationId_styleNbr(Long planId, Integer lvl3Nbr, Integer lvl4Nbr,Integer finelineNbr, String styleNbr);
}
