spring:
  profiles:
    active:
      - local
---
spring:
  main:
    allow-bean-definition-overriding: true
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none
    show-sql: true
  config:
    activate:
      on-profile: local
runtime:
  context:
    appVersion: 1.0.0-SNAPSHOT
    environment: DEV
    system:
      property:
        override:
          enabled: true
    environmentType: dev
    appName: aex-size-and-pack

scm:
  server:
    access:
      enabled: true
  snapshot:
    enabled: true

memcached.cache:
  servers: meghacache.dev.truedemand-dev.ms-df-cache.stg-az-eastus2-1.prod.us.walmart.net:24464
  provider: static
  expiration: 1d
---
spring:
  main:
    allow-bean-definition-overriding: true
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none
    show-sql: true
  config:
    activate:
      on-profile: dev

runtime:
  context:
    appVersion: 1.0.0-SNAPSHOT
    environment: DEV
    system:
      property:
        override:
          enabled: true
    environmentType: dev
    appName: aex-size-and-pack

scm:
  server:
    access:
      enabled: true
  snapshot:
    enabled: true

memcached.cache:
  servers: meghacache.dev.truedemand-dev.ms-df-cache.stg-az-eastus2-1.prod.us.walmart.net:24464
  provider: static
  expiration: 1d
---
spring:
  main:
    allow-bean-definition-overriding: true
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none
    show-sql: true
  config:
    activate:
      on-profile: stg

runtime:
  context:
    appVersion: 1.0.0-SNAPSHOT
    environment: STG
    system:
      property:
        override:
          enabled: true
    environmentType: stg
    appName: aex-size-and-pack

scm:
  server:
    access:
      enabled: true
  snapshot:
    enabled: true

memcached.cache:
  servers: meghacache.stg.truedemand-stg.ms-df-cache.stg-az-eastus2-1.prod.us.walmart.net:24464
  provider: static
  expiration: 1d
---
spring:
  main:
    allow-bean-definition-overriding: true
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none
    show-sql: true
  config:
    activate:
      on-profile: prod

runtime:
  context:
    appVersion: 1.0.0-SNAPSHOT
    environment: PROD
    system:
      property:
        override:
          enabled: true
    environmentType: prod
    appName: aex-size-and-pack

scm:
  server:
    access:
      enabled: true
  snapshot:
    enabled: true

memcached.cache:
  servers: meghacache.prod.truedemand-prod.ms-df-cache.prod-az-eastus2-1.prod.us.walmart.net:20192,meghacache.prod.truedemand-prod.ms-df-cache.prod-az-southcentralus-28.prod.us.walmart.net:20192
  provider: static
  expiration: 1d
---
management:
  health:
    db:
      enabled: false
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - loggers
          - metrics
          - prometheus
    health:
      show-details: always
  endpoint:
    loggers:
      enabled: true
