configuration:
  runtime: "concord-v2"
  arguments:
    group: "CN=GTAX_DEVS,.*"
    concordUrl: "https://concord.prod.walmart.com"
    concordTxnUrl: "${concordUrl}/#/process/${txId}"

profiles:
  dev:
    configuration:
      arguments:
        spBaseUrl: "aex-size-and-pack.aex.dev.walmart.net"
        spGraphQlEndpoint: "http://aex-size-and-pack.aex.dev.walmart.net/graphql"
        env: dev

publicFlows:
  - planAdminRuleForm

forms:
  addPlanAdminRuleForm:
    - planId: { label: "Specify Plan ID ", type: "int", min: 0, max: 99999 }
    - deptNbr: { label: "Specify Dept Nbr ", type: "int", min: 0, max: 99999 }
    - replenishmentItemPieceRule: { label: "Specify the replenishment item piece rule", type: "int", min: 0, max: 99999 }
    - minReplenishmentQtyByItem: { label: "Source the minimum replenishment Qty By Item", type: "int", min: 0, max: 99999 }

flows:
  addPlanAdminRulesToDB:
    - call: addPlanAdminRuleToDB
      in:
        planAdminRuleRequests: ${item}

  planAdminRuleForm:
    - call: validateProfile
    - form: addPlanAdminRuleForm
      runAs:
        ldap:
          - group: ${group}
    - log: "Starting - Adding Plan Admin Rules"
    - call: addPlanAdminRulesToDB
      in:
        planId: ${addPlanAdminRuleForm.planId}
        deptNbr: ${addPlanAdminRuleForm.deptNbr}
        replenishmentItemPieceRule: ${addPlanAdminRuleForm.replenishmentItemPieceRule}
        minReplenishmentQtyByItem: ${addPlanAdminRuleForm.minReplenishmentQtyByItem}

  validateProfile:
    - if: ${env.isEmpty()}
      then:
        - log: "Profile was not provided"
        - exit

  addPlanAdminRuleToDB:
    - log: "Adding Plan Admin rule: ${planAdminRuleRequests}"
    - task: http
      in:
        method: POST
        url: ${spGraphQlEndpoint}
        request: json
        body:
          destination:
            baseDivision: ${baseDivision}
            countryCode: ${countryCode}
            sourceStoreNumber: ${sourceStore}
            destinationStoreNumber: ${destinationStore}
        headers:
          content-type: "application/json",
          WM_CONSUMER.ID: "34f7ca77-3dfc-46df-a86b-1ba6e4908d0e",
          WM_SVC.NAME: "AEX_SIZE_AND_PACK",
          WM_SVC.ENV: "dev"
        response: string
      out: response
    - if: ${not response.ok}
      then:
        - log: "Add Plan Admin Rule Failed: ${response.error}"
      else:
        - log: "PlanId ${planId} was added Successfully: ${response}"
        - throw: "Following list of planIds received a non-200 response code: ${storesFailed} - Refer to logs for more info. "
